baseurl = "/"
languageCode = "en-us"
title = "Reasoning With React"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "jdhorwitz"
  GitlabId = "joshuahorwitz"
  TwitterID = "jdhorwitz"
  LinkedInID = "joshuahorwitz"
  Name = "Josh Horwitz"
  HeaderUsername = "josh"
  HeaderHostname = "joshuahorwitz.net"
  Email = "joshua.d.horwitz@gmail.com"
  About = "React and Javascript developer, with a passion for Ocaml and ReasonML"
  ProfilePicture = "https://media.licdn.com/media/p/8/005/0a5/169/368932c.jpg"
